"""T5.3 — programmatic persona session generator (calibrated, grounded).

A *persona* is a set of profile parameters (per-class miscue rates per 100 words,
self-correction propensity folded into the rates, hesitation rate, struggle
escalation propensity, band ceiling) loaded from ``data/personas/*.yaml``. The
rates are calibrated to published oral-reading distributions with the evidence-
vs-assumption boundary made explicit per field IN the YAML (see those files).

A *session item* is a passage (chosen to respect the persona's band ceiling —
that is the "never vocabulary above the level" grounding, by construction) plus a
seeded, word-by-word event stream in a SessionTrace-compatible shape: each
:class:`SessionEvent` carries a page position, an event kind (``clean`` /
one of the 5 detector miscue classes / ``page_end``), the running
consecutive-struggle count and page-had-struggle flag the tutor's hint ladder
consumes, and — for substitution / self_correction — a CONCRETE ``said_word``
generated by the :mod:`readcoach.inject` orthographic-neighbour machinery from the
passage's own words (never a placeholder).

Grounding, asserted in code
---------------------------
* every event kind is one of the 5 detector classes (``readcoach.miscue``) plus
  the two non-miscue kinds (``clean`` / ``page_end``);
* every concrete ``said_word`` is derived from a real target word in the passage
  (so the "said" vocabulary never exceeds the passage's band);
* :func:`generate_all` only pairs a persona with a passage whose band is at or
  below the persona's ceiling;
* :func:`assert_corpus_calibration` checks that the OBSERVED per-100 rates across
  the corpus sit within a documented tolerance of each persona's spec, and FAILS
  LOUD (``CalibrationError``) otherwise.

Determinism
-----------
Pure w.r.t. an injected ``random.Random``. :func:`generate_all` derives a child
RNG per (persona, passage, session_index) from the top-level seed via a stable
``SHA-256(seed, persona_id, passage_id, session_index)`` digest, so the corpus is
reproducible and order-independent.
"""
from __future__ import annotations

import hashlib
import random
from dataclasses import dataclass
from pathlib import Path

import yaml

from readcoach.inject import (
    Passage,
    _choose_self_correction_attempt,
    _choose_substitution,
    _split_affixes,
)
from readcoach.miscue import _ALL_CLASSES, MiscueType

# The two non-miscue event kinds the stream carries alongside the 5 detector
# classes. ``clean`` = a correctly-read word; ``page_end`` = a page boundary.
EventKind = str  # one of _ALL_CLASSES | {"clean", "page_end"}
_NON_MISCUE_KINDS: frozenset[str] = frozenset({"clean", "page_end"})

# Number of sessions generated per (persona, eligible-passage) pair.  See the
# corpus-size arithmetic in generate_all's docstring: 14 eligible pairs × 7 = 98
# items, inside the 90-120 target.
_DEFAULT_SESSIONS_PER_PAIR = 7

# Tolerance (fractional) within which observed per-100 rates must track the spec
# across the corpus.  ±50% — wide because a single short passage is a small
# sample, but the corpus aggregate is far tighter (documented in T5.3).
_DEFAULT_CALIBRATION_TOLERANCE = 0.5

# Minimum target-word length for an orthographic-neighbour miscue
# (substitution / self_correction): a 1-char word has no single-edit neighbour
# clearing inject.py's similarity gate.  Mirrors inject._MIN_NEIGHBOUR_LEN.
_MIN_NEIGHBOUR_LEN = 2


# ---------------------------------------------------------------------------
# Persona profile
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Persona:
    """A reader profile: calibrated per-class rates + behavioural propensities.

    ``rates`` maps each of the 5 detector miscue classes to its expected number
    of events per 100 running words.  ``band_ceiling`` caps which passages this
    persona may read (the grounding).  ``struggle_escalation_p`` is the
    probability a mid-page miscue extends a consecutive-struggle run (drives the
    tutor's hint ladder).
    """

    id: str
    label: str
    description: str
    band_ceiling: int
    rates: dict[MiscueType, float]
    struggle_escalation_p: float
    citations: tuple[str, ...]
    calibration_notes: tuple[str, ...]


def load_personas(dir: str | Path) -> list[Persona]:
    """Load every ``*.yaml`` persona in ``dir``, sorted by id (stable order).

    Fail-loud: a missing rate class, a missing required field, an out-of-range
    band ceiling, or a struggle probability outside [0, 1] raises rather than
    silently defaulting.
    """
    directory = Path(dir)
    files = sorted(directory.glob("*.yaml"))
    if not files:
        raise FileNotFoundError(f"No persona YAML files found in {directory!r}")

    personas: list[Persona] = []
    for f in files:
        raw = yaml.safe_load(f.read_text(encoding="utf-8"))
        if not isinstance(raw, dict):
            raise ValueError(
                f"{f.name}: expected a YAML mapping, got {type(raw).__name__}"
            )
        # Explicit key access — KeyError on any missing required field.
        pid = raw["id"]
        label = raw["label"]
        description = raw["description"].strip()
        band_ceiling = raw["band_ceiling"]
        raw_rates = raw["rates"]
        struggle_p = raw["struggle_escalation_p"]
        citations = raw["citations"]
        calibration_notes = raw["calibration_notes"]

        if band_ceiling not in (1, 2, 3, 4):
            raise ValueError(
                f"{f.name}: band_ceiling must be one of 1..4, got {band_ceiling!r}"
            )
        if not isinstance(raw_rates, dict):
            raise ValueError(f"{f.name}: 'rates' must be a mapping")
        # Every one of the 5 detector classes must be present (fail loud).
        rates: dict[MiscueType, float] = {}
        for cls in _ALL_CLASSES:
            if cls not in raw_rates:
                raise KeyError(f"{f.name}: rates missing required class {cls!r}")
            rate = float(raw_rates[cls])
            if rate < 0.0:
                raise ValueError(f"{f.name}: rate for {cls!r} must be >= 0, got {rate}")
            rates[cls] = rate
        unknown_rate = set(raw_rates) - set(_ALL_CLASSES)
        if unknown_rate:
            raise ValueError(
                f"{f.name}: unknown rate class(es) {sorted(unknown_rate)}"
            )
        if not (0.0 <= float(struggle_p) <= 1.0):
            raise ValueError(
                f"{f.name}: struggle_escalation_p must be in [0, 1], got {struggle_p!r}"
            )
        if not citations:
            raise ValueError(f"{f.name}: 'citations' must be a non-empty list")
        if not calibration_notes:
            raise ValueError(f"{f.name}: 'calibration_notes' must be a non-empty list")

        personas.append(
            Persona(
                id=pid,
                label=label,
                description=description,
                band_ceiling=band_ceiling,
                rates=rates,
                struggle_escalation_p=float(struggle_p),
                citations=tuple(citations),
                calibration_notes=tuple(calibration_notes),
            )
        )
    personas.sort(key=lambda p: p.id)
    return personas


# ---------------------------------------------------------------------------
# Session item / event shapes (SessionTrace-compatible)
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class SessionEvent:
    """One word-position (or page boundary) in a generated reading session.

    Fields mirror the decision context the tutor consumes (cf.
    ``scripts.generate_turns.Step``): ``at_page_end`` / ``consecutive_struggles``
    / ``page_had_struggle`` drive the policy; ``kind`` is the miscue class (or
    ``clean`` / ``page_end``); ``said_word`` carries the concrete misread word for
    substitution / self_correction (a real orthographic neighbour of the target).
    """

    page_index: int
    word_index: int          # target-word index in the passage (page_end: end pos)
    kind: EventKind          # _ALL_CLASSES | "clean" | "page_end"
    target_word: str | None  # normalized target word, or None for page_end
    said_word: str | None    # concrete misread word (sub/self_correction), else None
    at_page_end: bool
    consecutive_struggles: int
    page_had_struggle: bool


@dataclass(frozen=True)
class SessionItem:
    """A persona reading one passage: the seeded event stream + identity."""

    id: str
    persona_id: str
    passage_id: str
    band: int
    events: tuple[SessionEvent, ...]


def _to_event_dict(ev: SessionEvent) -> dict:
    return {
        "page_index": ev.page_index,
        "word_index": ev.word_index,
        "kind": ev.kind,
        "target_word": ev.target_word,
        "said_word": ev.said_word,
        "at_page_end": ev.at_page_end,
        "consecutive_struggles": ev.consecutive_struggles,
        "page_had_struggle": ev.page_had_struggle,
    }


def session_item_to_dict(item: SessionItem) -> dict:
    """JSON-serializable dict form of a SessionItem (lists, not tuples)."""
    return {
        "id": item.id,
        "persona_id": item.persona_id,
        "passage_id": item.passage_id,
        "band": item.band,
        "events": [_to_event_dict(ev) for ev in item.events],
    }


# ---------------------------------------------------------------------------
# Page segmentation (sentences = "pages")
# ---------------------------------------------------------------------------

_SENTENCE_ENDERS = (".", "!", "?")


def _page_boundaries(words: tuple[str, ...]) -> list[int]:
    """Return the set of word indices AFTER which a page ends.

    A page boundary is the last word of a sentence (token ending in . ! ?).  The
    final word always ends a page even if it lacks terminal punctuation.
    """
    bounds: list[int] = []
    for i, w in enumerate(words):
        if w.rstrip("\"'").endswith(_SENTENCE_ENDERS):
            bounds.append(i)
    if not bounds or bounds[-1] != len(words) - 1:
        bounds.append(len(words) - 1)
    return bounds


# ---------------------------------------------------------------------------
# Per-word miscue sampling
# ---------------------------------------------------------------------------

def _sample_kind(
    persona: Persona,
    target_core: str,
    rng: random.Random,
) -> MiscueType | None:
    """Sample at most one miscue class for a word, given the persona's per-100 rates.

    Each class fires independently with p = rate/100.  If several fire on the same
    word, detector precedence (self_correction > hesitation > substitution >
    insertion > omission) picks one — at most one miscue per word, matching the
    detector's one-miscue-per-token rule.  Neighbour classes (substitution /
    self_correction) are skipped on words too short to clear the similarity gate
    (they fall through to the next-precedence class or to clean).
    """
    fired: set[MiscueType] = set()
    for cls in _ALL_CLASSES:
        p = persona.rates[cls] / 100.0
        if p <= 0.0:
            continue
        if rng.random() < p:
            fired.add(cls)

    # Drop neighbour-class fires on too-short words (no valid orthographic
    # neighbour) so we never emit a placeholder said_word.
    if len(target_core) < _MIN_NEIGHBOUR_LEN:
        fired.discard("substitution")
        fired.discard("self_correction")

    if not fired:
        return None
    # Detector one-token precedence.
    for cls in ("self_correction", "hesitation", "substitution", "insertion", "omission"):
        if cls in fired:
            return cls
    return None  # pragma: no cover — fired is a subset of the precedence list


# ---------------------------------------------------------------------------
# Session generation
# ---------------------------------------------------------------------------

def generate_session(
    persona: Persona,
    passage: Passage,
    rng: random.Random,
    *,
    session_index: int,
) -> SessionItem:
    """Generate one seeded reading session of ``persona`` over ``passage``.

    Pure w.r.t. ``rng``.  Walks the passage word-by-word, sampling at most one
    miscue per word from the persona's per-100 rates, emitting ``clean`` for the
    rest and a ``page_end`` event at each sentence boundary.  Substitution /
    self_correction said_words are real orthographic neighbours from
    :mod:`readcoach.inject`.  Tracks the consecutive-struggle run and
    page-had-struggle flag the tutor consumes.
    """
    if passage.band > persona.band_ceiling:
        raise ValueError(
            f"persona {persona.id} (ceiling {persona.band_ceiling}) cannot read "
            f"passage {passage.id} (band {passage.band}) — band-ceiling grounding"
        )

    words = passage.words
    n = len(words)
    cores = [_split_affixes(w)[1] for w in words]
    page_ends = set(_page_boundaries(words))

    events: list[SessionEvent] = []
    page_index = 0
    consecutive = 0
    page_had_struggle = False

    for i in range(n):
        core = cores[i]
        prev_core = cores[i - 1] if i > 0 else None
        kind = _sample_kind(persona, core, rng)

        said_word: str | None = None
        target_word: str | None = core

        if kind is None:
            ev_kind: EventKind = "clean"
            consecutive = 0
        else:
            ev_kind = kind
            if kind == "substitution":
                said_word = _choose_substitution(core, rng)
            elif kind == "self_correction":
                said_word = _choose_self_correction_attempt(core, prev_core, rng)
            elif kind in ("insertion", "hesitation"):
                # Insertion/hesitation are not bound to a misread target word
                # token; the detector emits target_word=None for these.
                target_word = None
            # omission keeps target_word = core, said_word = None.

            # Does this miscue extend a consecutive-struggle run?  Escalation is a
            # seeded Bernoulli on the persona's propensity; a non-escalating miscue
            # is a one-off (counter resets).
            if rng.random() < persona.struggle_escalation_p:
                consecutive += 1
            else:
                consecutive = 0
            page_had_struggle = page_had_struggle or consecutive > 0

        at_page_end = i in page_ends
        events.append(
            SessionEvent(
                page_index=page_index,
                word_index=i,
                kind=ev_kind,
                target_word=target_word,
                said_word=said_word,
                at_page_end=at_page_end,
                consecutive_struggles=consecutive,
                page_had_struggle=page_had_struggle,
            )
        )

        if at_page_end:
            # Emit an explicit page_end event carrying the page's struggle context.
            events.append(
                SessionEvent(
                    page_index=page_index,
                    word_index=i,
                    kind="page_end",
                    target_word=None,
                    said_word=None,
                    at_page_end=True,
                    consecutive_struggles=consecutive,
                    page_had_struggle=page_had_struggle,
                )
            )
            page_index += 1
            consecutive = 0
            page_had_struggle = False

    item_id = f"{persona.id}__{passage.id}__s{session_index}"
    return SessionItem(
        id=item_id,
        persona_id=persona.id,
        passage_id=passage.id,
        band=passage.band,
        events=tuple(events),
    )


def _child_rng(seed: int, persona_id: str, passage_id: str, session_index: int) -> random.Random:
    """Derive a per-(persona, passage, session) RNG from the top-level seed.

    Order-independent: a SHA-256 digest of the tuple seeds the child RNG, so the
    corpus is identical regardless of iteration order.
    """
    key = f"{seed}:{persona_id}:{passage_id}:{session_index}".encode()
    digest = hashlib.sha256(key).digest()
    return random.Random(int.from_bytes(digest[:8], "big"))


def generate_all(
    personas: list[Persona],
    passages: list[Passage],
    *,
    seed: int,
    sessions_per_persona_passage: int = _DEFAULT_SESSIONS_PER_PAIR,
) -> list[SessionItem]:
    """Generate every persona session item; deterministic for a fixed seed.

    Corpus-size arithmetic (with the committed data: 8 passages, bands
    1,1,2,2,3,3,4,4 for p01..p08):
      * eligible (persona, passage) pairs = passages with band <= ceiling:
          emergent (ceiling 2)         -> 4 passages (p01,p02,p03,p04)
          ell_profile (ceiling 3)      -> 6 passages (p01..p06)
          dyslexic_profile (ceiling 2) -> 4 passages (p01,p02,p03,p04)
        = 4 + 6 + 4 = 14 eligible pairs.
      * sessions_per_persona_passage = 7 (the default)  ->  14 × 7 = 98 items,
        inside the 90-120 target.  Per-persona spread: emergent 28, ell_profile
        42, dyslexic_profile 28 — every persona gets >= 28 sessions, ample for the
        corpus-level calibration check.

    Each (persona, passage, session_index) gets an independent SHA-256-derived
    child RNG, so the corpus is identical regardless of iteration order.
    """
    # Sort for a stable, order-independent corpus.
    personas_sorted = sorted(personas, key=lambda p: p.id)
    passages_sorted = sorted(passages, key=lambda p: p.id)

    items: list[SessionItem] = []
    for persona in personas_sorted:
        eligible = [pg for pg in passages_sorted if pg.band <= persona.band_ceiling]
        for passage in eligible:
            for s in range(sessions_per_persona_passage):
                rng = _child_rng(seed, persona.id, passage.id, s)
                items.append(
                    generate_session(persona, passage, rng, session_index=s)
                )
    # Stable sort by id for a deterministic, order-independent return.
    items.sort(key=lambda it: it.id)
    return items


# ---------------------------------------------------------------------------
# Corpus calibration assertion (no bypass)
# ---------------------------------------------------------------------------

class CalibrationError(Exception):
    """Raised when observed per-100 miscue rates drift outside the tolerance."""


def observed_rates(items: list[SessionItem]) -> dict[str, dict[str, float]]:
    """Per-persona observed miscue rate per 100 running words, by class.

    Denominator = total running words read by that persona across the corpus
    (every ``clean`` event plus every per-word miscue event; ``page_end`` events
    are not words).  Returns ``{persona_id: {class: rate_per_100}}``.
    """
    word_events = set(_ALL_CLASSES) | {"clean"}
    totals: dict[str, int] = {}
    counts: dict[str, dict[str, int]] = {}
    for it in items:
        totals.setdefault(it.persona_id, 0)
        counts.setdefault(it.persona_id, {cls: 0 for cls in _ALL_CLASSES})
        for ev in it.events:
            if ev.kind in word_events:
                totals[it.persona_id] += 1
            if ev.kind in _ALL_CLASSES:
                counts[it.persona_id][ev.kind] += 1

    out: dict[str, dict[str, float]] = {}
    for pid, total in totals.items():
        if total == 0:
            raise CalibrationError(f"persona {pid}: no running words read")
        out[pid] = {
            cls: counts[pid][cls] / total * 100.0 for cls in _ALL_CLASSES
        }
    return out


def assert_corpus_calibration(
    personas: list[Persona],
    passages: list[Passage],  # noqa: ARG001 — kept for a self-describing signature
    items: list[SessionItem],
    *,
    tolerance: float = _DEFAULT_CALIBRATION_TOLERANCE,
) -> dict[str, dict[str, float]]:
    """Assert the OBSERVED per-100 rates track each persona's spec within tolerance.

    For every persona and every of the 5 classes, the observed corpus rate must
    satisfy ``|observed - spec| <= tolerance * spec`` (with a small absolute floor
    so a spec of, say, 1.0/100 is not held to an impossibly tight band on a finite
    sample).  Raises :class:`CalibrationError` naming the first violating
    (persona, class) — there is NO flag to skip this check.

    Returns the observed-rate matrix on success.
    """
    by_id = {p.id: p for p in personas}
    obs = observed_rates(items)

    # Absolute floor (events/100): on a finite corpus a low-rate class has high
    # relative variance, so allow at least this much absolute slack.
    abs_floor = 1.0

    for pid, persona in by_id.items():
        if pid not in obs:
            raise CalibrationError(f"persona {pid}: no items in corpus")
        for cls in _ALL_CLASSES:
            spec = persona.rates[cls]
            observed = obs[pid][cls]
            allowed = max(tolerance * spec, abs_floor)
            if abs(observed - spec) > allowed:
                raise CalibrationError(
                    f"persona {pid} class {cls}: observed {observed:.2f}/100 "
                    f"outside spec {spec:.2f} ± {allowed:.2f} (tolerance "
                    f"{tolerance:.0%}, abs floor {abs_floor})"
                )
    return obs
